### ISSUE TITLE
Connecting hang with 0.27?

### ISSUE THREAD

**Issue by dmurphynj** [tchellomello/python-ring-doorbell#154]
Python 3.8 installed, using a venv.

I'm trying to toggle my floodlights on/off, and appear to be hanging somewhere in the authorization code.  It's hideously ugly code but has been working for a long time until Ring started messing with us.
````
#!/srv/homeassistant/bin/python3.8
import sys
from ring_doorbell import Ring
myring = Ring('<<USERNAME>>', '<<PASSWORD>>')

## Since I only have one Stickup cam (Backyard) we can pluck the first off the array.

dev = myring.stickup_cams[0]

dev.update()
if dev.lights == 'on':
	dev.lights = 'off'
	sys.exit(1)
else:
	dev.lights = 'on'
	sys.exit(0)
````

I have to CTRL-C to exit the hung Python session:

````
(homeassistant) homeassistant@dmurphy-home:~/.homeassistant/python_scripts$ ./ringtoggle.py 
^CTraceback (most recent call last):
  File "./ringtoggle.py", line 10, in <module>
    dev.update()
  File "/srv/homeassistant/lib/python3.8/site-packages/ring_doorbell/generic.py", line 56, in update
    self._get_health_attrs()
  File "/srv/homeassistant/lib/python3.8/site-packages/ring_doorbell/generic.py", line 103, in _get_health_attrs
    self._health_attrs = self._ring.query(url).get('device_health')
  File "/srv/homeassistant/lib/python3.8/site-packages/ring_doorbell/__init__.py", line 198, in query
    'Bearer {}'.format(self._get_oauth_token())
  File "/srv/homeassistant/lib/python3.8/site-packages/ring_doorbell/__init__.py", line 111, in _get_oauth_token
    self.auth = oauth.refresh_tokens()
  File "/srv/homeassistant/lib/python3.8/site-packages/ring_doorbell/auth.py", line 59, in refresh_tokens
    token = self._oauth.refresh_token(OAuth.ENDPOINT)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 426, in refresh_token
    r = self.post(
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1933, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
KeyboardInterrupt
````

Any ideas what we're hanging on?

**Comment by steve-gombos** [comment]
It looks like @tchellomello came across some issues with different versions of these libraries compared to Home Assistant the other day.  Are you still seeing this?  You could try removing the cache file and starting fresh?

**Comment by odenisenko** [comment]
add timeout=5 to all requests in __init__.py  that's could solve your issues

**Comment by dmurphynj** [comment]
So for whatever reason, I'm not having timeout hangs today.  The above script is running just fine.

Long story short, I have a Ring floodlight over my deck.  The problem is, there's a switch just inside the door that controls said floodlight.  Unfortunately switching it off powers off everything, including the camera.  So I removed the switch, installed a WeMo switch, but pigtailed the light in so the WeMo doesn't actually switch the power on/off; all it does in this case is fire off an event.

Here's my quick-n-dirty Homeassistant integration that toggles the Ring floodlight on and off when the WeMo switch (entity switch.deck_light) gets a press:

automation.yaml:
````
 - alias: 'Deck Switch On'
    trigger:
      - platform: state
        entity_id: switch.deck_light
        from: 'off'
        to: 'on'
    action: 
        service: shell_command.ring_on
  
  - alias: 'Deck Switch Off'
    trigger:
      - platform: state
        entity_id: switch.deck_light
        from: 'on'
        to: 'off'
    action: 
        service: shell_command.ring_off
````

configuration.yaml:
````
shell_command:
  ring_on: /home/homeassistant/.homeassistant/python_scripts/ringon.py
  ring_off: /home/homeassistant/.homeassistant/python_scripts/ringoff.py
````
ringon.py:
````
#!/srv/homeassistant/bin/python3.8
import sys
from ring_doorbell import Ring
myring = Ring('<<LOGIN>>', '<<PASSWORD>>')

## Since I only have one Stickup cam (Backyard) we can pluck the first off the array.

dev = myring.stickup_cams[0]

dev.update()
dev.lights = 'on'
sys.exit(0)
````

ringoff.py
````
#!/srv/homeassistant/bin/python3.8
import sys
from ring_doorbell import Ring
myring = Ring('<<LOGIN>>', '<<PASSWORD>>')

## Since I only have one Stickup cam (Backyard) we can pluck the first off the array.

dev = myring.stickup_cams[0]

dev.update()
dev.lights = 'off'
sys.exit(0)
````

**Comment by tchellomello** [comment]
> add timeout=5 to all requests in **init**.py that's could solve your issues

The PR #165 should take care of that

**Comment by tchellomello** [comment]
Closing this issue for now. Please feel free to reopen if it still is happening.
