### ISSUE TITLE
v0.2.9 invalid syntax error in __init__.py

### ISSUE THREAD

**Issue by ZachBenz** [tchellomello/python-ring-doorbell#162]
Per ZachBenz/RingForIndigo#5 - when using latest version (0.2.9) of @tchellomello python-ring-doorbell as part of a plugin for Indigo home automation server, get an invalid syntax error:

```
Ring Error                      Error in plugin execution InitializeMain:

Traceback (most recent call last):
  File "plugin.py", line 15, in <module>
SyntaxError: ('invalid syntax', ('/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py', 35, 31, '                 auth_callback: Callable[[], str] = None,\n'))
```

**Comment by ZachBenz** [comment]
Looks like this is a Python 2 vs. Python 3 issue:

> Type annotations are unsupported in Python 2

**Comment by steve-gombos** [comment]
Not familiar with python 2, but I'm assuming it is just remove the typing library since there probably isn't a commonality between the two?

**Comment by ZachBenz** [comment]
@steve-gombos Thanks; in python 2 you do typing in the docstring (vs. inline with the parameter definition) - I'm trying out moving things there to see how it works out.

Seems to be a separate OAUTH scope typing issue as well that I'm puzzling through.

**Comment by ZachBenz** [comment]
Converting typing to old-school python 2 docstring syntax fixed that issue.

However, the OAUTH scope issue is a python string (double quote) vs. regex (single quote) issue - that is, const.py is specifying OAuth.SCOPE as 'client', not "client", which is resulting in a type mismatch in the validation matching code of oauthlib's list_to_scope method (which explicitly looks for a str)

  ```
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/utils.py", line 30, in list_to_scope
ValueError: Invalid scope (client), must be string, tuple, set, or list.
```

Changing it to "client" fixes this.  But then a new issue comes up:

 ```
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/errors.py", line 325, in raise_from_error
UnauthorizedClientError: (unauthorized_client) The client is not authorized to request a token using this method.
```

**Comment by steve-gombos** [comment]
@ZachBenz Yeah I see the typing issue with the scope param.  Could you pass this in as a list?  I check the oauthlib and this should technically be a list.  SCOPE = ['client']  in const

**Comment by ZachBenz** [comment]
@steve-gombos Yep, passing in as a list works, thanks!  Still trying to figure out the unauthorized_client issue.

**Comment by ZachBenz** [comment]
Longer error trace showing how it rolls down from __init__.py down into oauthlib

```
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 64, in __init__
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 100, in _process_cached_session
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 130, in _authenticate
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 111, in _get_oauth_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 36, in fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 67, in __fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/oauthlib/oauth2/rfc6749/errors.py", line 325, in raise_from_error
UnauthorizedClientError: (unauthorized_client) The client is not authorized to request a token using this method.
```

**Comment by ZachBenz** [comment]
Ah - seems like I have an imcompatible (older) version of oauthlib; fixing that...

**Comment by ZachBenz** [comment]
Ok, got right library versions in place (using requirements.txt).  I'm going to create a pull request including:

- Switch to python 2 compatible typing in docstrings
- Add in the fix for the OAuth.SCOPE (make it a list)
