### ISSUE TITLE
0.2.9 breaks recording_download

### ISSUE THREAD

**Issue by ZachBenz** [tchellomello/python-ring-doorbell#171]
#165 breaks video download due to the short timeout (timeout=5 is too short for the lengthy video download)

Exception traceback as seen in usage of ring_doorbell 0.2.9 within Indigo Home Automation Server plugin ZachBenz/RingForIndigo:
```
Traceback (most recent call last):
  File "plugin.py", line 627, in downloadVideoForEvent
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/doorbot.py", line 301, in recording_download
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 238, in query
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 546, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 533, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 646, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/adapters.py", line 529, in send
ReadTimeout: HTTPSConnectionPool(host='api.ring.com', port=443): Read timed out. (read timeout=5)
```

**Comment by tchellomello** [comment]
@ZachBenz  thanks for the heads up.  Maybe we can override the timeout for the `recording_download` method so we can still be good with other calls. What do you think?

**Comment by ZachBenz** [comment]
@tchellomello Agreed - I was just implementing something like this.  I added an optional timeout parameter to __init__.py's query method.  If it is None, we just stick with self._timeout; otherwise, we use what was passed in (e.g. from recording_download)

**Comment by tchellomello** [comment]
@ZachBenz  awesome. Let's wait for your PR then so we can get this fixed :)  you++

**Comment by ZachBenz** [comment]
I'm taking a rough guess at what a decent timeout for video download is (I'm on a very fast network connection, so my test environment is a bad general example).  My rough guess for general use is that 3 minutes should be enough; setting it as const in const.py so we can fiddle with it as needed.

**Comment by ZachBenz** [comment]
Thinking about this a little more, I'm going to add an optional timeout param to recording_download as well so that end users can vary it as need be.  Will keep a default 3 minute VIDEO_DOWNLOAD_TIMEOUT, but at least this gives flexibility in implementation...

**Comment by ZachBenz** [comment]
Did some calculations - .mp4 file size for video is on the order of 10 MB.  The official US FCC definition of broadband is a minimum of 25 Mbps down (and 3 Mbps up).  @ 25 Mbps, the video file should take a bit over 5 seconds to download... but, this assumes you are getting the full bandwidth for the download.  Using a factor of 10 as a safe margin, we get about 50 seconds (let's call it a minute) for video download timeout.  Thus, I'll make DEFAULT_VIDEO_DOWNLOAD_TIMEOUT=60 (and also provide an optional timeout parameter for recording_download)

**Comment by ZachBenz** [comment]
Testing some more, an actual download of a 11.2 MB video on my dev system took 15 seconds, with the limiting factor on speed likely being the Ring backend.  Multiplying by a safety factor of 10, that puts us at 150 seconds.  Let's call it about 2 minutes.  

Ok, I'm done fiddling. :-)  Getting a PR ready.

**Comment by ZachBenz** [comment]
@tchellomello I believe the PR is now good to go
