### ISSUE TITLE
0.5 Release breaks HA integration (SOLVED)

### ISSUE THREAD

**Issue by tescophil** [tchellomello/python-ring-doorbell#183]
Don't know if its just me, but I've installed 0.5 in HA via pip install (as per the read me) and it falls at the first fence. Previous version was working, apart from motion and ding sensors.

I see that 0.5 is listed as a 'Breaking Change', so is this the expected behaviour ?, and we will have to wait for an update of Home Assistant before it's working again ?

SOLVED: Answering my own question here. YES, this is meant as a breaking change. Moved to the Beta channel of home assisting to get the latest version. Then you must remove any ring specific config from your configuration.yaml (everything under ring: as well as sensor: and binary_sensor entries), then reboot and install via the HA Integrations Page.

```
2020-01-13 14:07:06 ERROR (MainThread) [homeassistant.setup] Error during setup of component ring
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ring/__init__.py", line 55, in setup
    ring = Ring(username=username, password=password, cache_file=cache)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 69, in __init__
    self._process_cached_session()
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 105, in _process_cached_session
    self._authenticate()
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 145, in _authenticate
    'Bearer {}'.format(self._get_oauth_token())
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 116, in _get_oauth_token
    self.auth_callback)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/auth.py", line 34, in fetch_token
    return self.__fetch_token(username, password)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/auth.py", line 65, in __fetch_token
    scope=OAuth.SCOPE)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by steve-gombos** [comment]
The HA integration is now done through the HA integration page with a config flow. You will need HA version 0.104. 

The exception above is also being thrown from an older release and not 0.5 just looking at the stack trace.

Going to close this.
