### ISSUE TITLE
Auth is not working

### ISSUE THREAD

**Issue by Darkem1** [tchellomello/python-ring-doorbell#195]
Hi together,
I just tried to get the new version running, but everytime I try to authenticate, there is an error. This is what the "test.py" puts out:

```
Traceback (most recent call last):
  File "test2.py", line 46, in <module>
    main()
  File "test2.py", line 31, in main
    auth = Auth(None, token_updated)
  File "/usr/local/lib/python3.6/site-packages/ring_doorbell/auth.py", line 21, in __init__
    client=LegacyApplicationClient(client_id=OAuth.CLIENT_ID), token=token
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 79, in __init__
    self.token = token or {}
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 129, in token
    self._client.populate_token_attributes(value)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable
```

What do I have to do? I don't have the 2FA

Thank you!

**Comment by steve-gombos** [comment]
Auth takes 3 params. You are missing a user agent.

**Comment by Darkem1** [comment]
Okay, is this documented somewhere? I tried every readme or test.py from here but I have always the same error.

**Comment by steve-gombos** [comment]
A couple weeks ago the documentation and examples were all updated. Have you pulled the latest?

**Comment by Darkem1** [comment]
Yes, I pulled the latest release. When I execute the "test.py" I get this error. 
When I copy the "Initializing your Ring object" from the readme, I get this error.

**Comment by steve-gombos** [comment]
If you could post your code, would help figure out your issue.  Just based on the error above I know that is because the user agent isn't being sent in auth as this was seen from here: https://github.com/tchellomello/python-ring-doorbell/issues/190#issuecomment-575931426
