### ISSUE TITLE
auth issues: TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by budachst** [tchellomello/python-ring-doorbell#202]
I have downloaded the test.py example and tried it on my host, but each time I am getting an error about 3 positional arguments being expected, but 4 arguments being provided:

```
root@fhem:/usr/local/ring# python3 test.py
Username: test
Password:
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    main()
  File "test.py", line 27, in main
    auth = Auth("MyProject/1.0", None, token_updated)
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given
```

Any idea, what could cause this?

**Comment by budachst** [comment]
Ahh… silly me… I invoked Python3.5 instead of 3.7.
