### ISSUE TITLE
Not able to authenticate

### ISSUE THREAD

**Issue by evdven** [tchellomello/python-ring-doorbell#203]
I'm running the latest release (0.6.0) of this lib and trying to get the ring api working again. Running the corresponding example test.py results in the following error: 

Traceback (most recent call last):
  File "dev/python/test.py", line 45, in <module>
    main()
  File "dev/python/test.py", line 31, in main
    auth = Auth(None, token_updated)
  File "/home/pi/.local/lib/python3.5/site-packages/ring_doorbell/auth.py", line 21, in __init__
    client=LegacyApplicationClient(client_id=OAuth.CLIENT_ID), token=token
  File "/home/pi/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 79, in __init__
    self.token = token or {}
  File "/home/pi/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 129, in token
    self._client.populate_token_attributes(value)
  File "/home/pi/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable

Any idea what I'm doing wrong?

**Comment by dshokouhi** [comment]
@evdven python 3.5 is not supported in the latest version.

**Comment by evdven** [comment]
@dshokouhi thanks for your hint. However moving it to python3.8 still seems to results in similar error. The funny thing is I'm running the corresponding [test.py](https://github.com/tchellomello/python-ring-doorbell/blob/master/test.py) script. Can you test if this works on your end? 

Traceback (most recent call last):
  File "test_org.py", line 46, in <module>
    main()
  File "test_org.py", line 31, in main
    auth = Auth(None, token_updated)
  File "/usr/local/lib/python3.8/site-packages/ring_doorbell/auth.py", line 20, in __init__
    self._oauth = OAuth2Session(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 79, in __init__
    self.token = token or {}
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 129, in token
    self._client.populate_token_attributes(value)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable

**Comment by steve-gombos** [comment]
Python 3.5 support was removed.  I haven't tested with 3.8.  But regardless you are missing the the user agent constructor param on Auth.

**Comment by evdven** [comment]
@steve-gombos thanks this does the trick! Now it works on 3.8 :)
