### ISSUE TITLE
get_snapshot method of doorbot class doesn't work

### ISSUE THREAD

**Issue by zhenqidong** [tchellomello/python-ring-doorbell#210]
```
>>> type(f)
<class 'ring_doorbell.doorbot.RingDoorBell'>

>>> c=f.get_snapshot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gamma/projects/python/ring/lib/python3.6/site-packages/ring_doorbell/doorbot.py", line 427, in get_snapshot
    self._ring.query(url)
  File "/home/gamma/projects/python/ring/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 101, in query
    timeout=timeout,
  File "/home/gamma/projects/python/ring/lib/python3.6/site-packages/ring_doorbell/auth.py", line 89, in query
    req.raise_for_status()
  File "/home/gamma/projects/python/ring/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.ring.com/clients_api/snapshots/timestamps?api_version=9
```

**Comment by hesto2** [comment]
Having the same issue

**Comment by budachst** [comment]
Have you patched the doorbot.py as shown here: [https://github.com/tchellomello/python-ring-doorbell/pull/196/files](url)?

**Comment by clinkadink** [comment]
This may (or may not) help.
https://github.com/tchellomello/python-ring-doorbell/issues/214#issuecomment-650620143
