### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hi337** [tchellomello/python-ring-doorbell#240]
Hello. I am using this api for the second time, the last time being many months ago. Since it's a new project, I started from scratch and took the script for "Initializing the Ring object" from this repo's README file. I used the script, entered the proper information and was hit with the following typeerror:

Traceback (most recent call last):
  File "c:/Coding Stuff/Python Freetime Projects and Learning/Ring Local/Ring.py", line 42, in <module>
    main()
  File "c:/Coding Stuff/Python Freetime Projects and Learning/Ring Local/Ring.py", line 35, in main
    ring.update_data()
  File "C:\Users\rateb\AppData\Local\Programs\Python\Python38\lib\site-packages\ring_doorbell\__init__.py", line 58, in update_data
    self.update_groups()
  File "C:\Users\rateb\AppData\Local\Programs\Python\Python38\lib\site-packages\ring_doorbell\__init__.py", line 99, in update_groups
    for group in data["device_groups"]:
TypeError: 'NoneType' object is not iterable

It seems like the script is making my token and logging me in properly but stops when it hits the 'update_data' method.

I installed the last version of this package (version 0.6.2) and the script worked just fine. The product in a Ring Doorbell 2 and the firmware is up to date.

**Comment by alexmanzer** [comment]
Hi,
I have the same problems with the update from 0.6.0 to 0.7.0.

`Traceback (most recent call last):
  File "check_doorbell_battery.py", line 45, in <module>
    main()
  File "check_doorbell_battery.py", line 35, in main
    ring.update_data()
  File "/home/pi/.local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 58, in update_data
    self.update_groups()
  File "/home/pi/.local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 99, in update_groups
    for group in data["device_groups"]:
TypeError: 'NoneType' object is not iterable`

**Comment by likan999** [comment]
Same problem seen here since upgraded to 0.7.0.

**Comment by hi337** [comment]
I know that the problem is coming for the update_groups() method. I looked and compared __init__.py for both the 0.7.0 and 0.6.2 versions but didn't have time to look at it completely. The method is not in the 0.6.2 version. Does anyone have any idea what it does and why its returning the type error?

**Comment by framllat** [comment]
Just downloaded 0.7.0

Same issue when running ringcli.py:
...TypeError: 'NoneType' object is not iterable```

**Comment by graham33** [comment]
Seeing the same thing when using this from the Home Assistant 2021.2.3 ring integration, works fine with 0.6.2.

**Comment by framllat** [comment]
Hi -- I'm not very well versed in the workings of code release within GIT.
As noted before I recently pulled the 0.7.0 code as I'm interested in trying my hand at working python with my Ring Doorbell.

If I run the code I get the TypeError: "NoneType" error.

I see some activity down the line about a bug label and a Feature/add being merged and another note requesting a downgrade to 0.6.2. And it is closed.

I'm new to trying to understand GIT and these manuverings...

Anyone have some cycles to describe what this means? Do you do some sort of 'downgrade' to get the 0.6.2 code to work?

Thanks for any insight.

**Comment by graham33** [comment]
If you're asking how to downgrade your local git clone to 0.6.2, you can just do `git checkout 0.6.2` to checkout the 0.6.2 tag.  See https://stackoverflow.com/questions/35979642/what-is-git-tag-how-to-create-tags-how-to-checkout-git-remote-tags for some more information on tags.

**Comment by framllat** [comment]
I guess I continue to struggle here.
Yes I want to run the 0.6.2 version as it continues to error on 0.7.0

I installed originally on a Centos VM - according to the docs:
pip install \
    git+https://github.com/tchellomello/python-ring-doorbell@master

Here is where I struggle to move the install back to the 0.6.2 version.

git checkout 0.6.2 doesn't work as I expect I didn't originally install it with native git?

Still puzzling.

**Comment by graham33** [comment]
`git+https://github.com/tchellomello/python-ring-doorbell@0.6.2` should work AFAIK

**Comment by framllat** [comment]
I tried that but got no such file or directory - However this worked:
pip3 install git+https://github.com/tchellomello/python-ring-doorbell@0.6.2

Got info that it found 0.7.0 and uninstalled and successfully installed 0.6.2

Thanks!

**Comment by prwood80** [comment]
I added a check that should address this as part of Pull Request #253
