### ISSUE TITLE
Download don't work

### ISSUE THREAD

**Issue by nhet** [tchellomello/python-ring-doorbell#242]
Since the last couple of days I get the following errors:
ring_doorbell.doorbot - ERROR - 404 Client Error: Not Found for url: https://api.ring.com/clients_api/dings/<DING_ID>/recording?api_version=9

**Comment by dude123studios** [comment]
Same

**Comment by nhet** [comment]
It's interesting and strange at the same time. The downloads often work after exactly 30 minutes.

**Comment by Gamerios** [comment]
**any news ?`for fix ?**

**Comment by nhet** [comment]
I don't know. It looks like @tchellomello is looking for a new maintainer.

**Comment by Gamerios** [comment]
now nothing work anymore always

`Traceback (most recent call last):
  File "ring-videos-download.py", line 91, in <module>
    main()
  File "ring-videos-download.py", line 64, in main
    events = deck.history(older_than=eid, limit=CHUNK_SIZE)
  File "/root/ringdownload/ring_doorbell/doorbot.py", line 262, in history
    response = self._ring.query(url, extra_params=params).json()
  File "/root/ringdownload/ring_doorbell/__init__.py", line 106, in query
    return self.auth.query(
  File "/root/ringdownload/ring_doorbell/auth.py", line 99, in query
    req.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.ring.com/clients_api/doorbots/619770/history?api_version=9&limit=200&older_than=6954438095398630081
`
