### ISSUE TITLE
Missing access token parameter

### ISSUE THREAD

**Issue by niro1987** [tchellomello/python-ring-doorbell#264]
As mentioned in #263, I'm trying to help out on a Feature Request but am running into below error. Can you help out in resolving this issue please?

```text
(python-ring-doorbell) C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell>python test.py
Username: <HIDDEN>
Password: 
2FA code: <HIDDEN>
Traceback (most recent call last):
  File "C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell\test.py", line 29, in main
    auth.fetch_token(username, password)
  File "C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell\ring_doorbell\auth.py", line 41, in fetch_token
    token = self._oauth.fetch_token(
  File "C:\Users\Niels\Anaconda3\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 429, in parse_request_body_response    
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 435, in validate_token_parameters        
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell\test.py", line 49, in <module>
    main()
  File "C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell\test.py", line 31, in main
    auth.fetch_token(username, password, otp_callback())
  File "C:\Users\Niels\OneDrive\Documenten\Python\python-ring-doorbell\ring_doorbell\auth.py", line 41, in fetch_token
    token = self._oauth.fetch_token(
  File "C:\Users\Niels\Anaconda3\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 429, in parse_request_body_response    
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Niels\Anaconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by niro1987** [comment]
#251
