### ISSUE TITLE
Error running cli

### ISSUE THREAD

**Issue by BillyCroan** [tchellomello/python-ring-doorbell#302]
Traceback when importing ring_doorbell:
    root@RingPi:~/gits/python-ring-doorbell# python
    Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ring_doorbell
    Traceback (most recent call last):
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
        return next(cls.discover(name=name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    StopIteration
    ​
    During handling of the above exception, another exception occurred:
    ​
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/root/gits/python-ring-doorbell/ring_doorbell/__init__.py", line 4, in <module>
        __version__ = version("ring_doorbell")
                      ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
        return distribution(distribution_name).version
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
        return Distribution.from_name(distribution_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
        raise PackageNotFoundError(name)
    importlib.metadata.PackageNotFoundError: No package metadata was found for ring_doorbell
    >>>

**Comment by sdb9696** [comment]
Hi, have you actually installed the package?  It doesn't seem like it.  You can either install via pip or poetry, there are instructions in the README or CONTRIBUTING files depending on which method you want to use.
