### ISSUE TITLE
getting error running initiation 

### ISSUE THREAD

**Issue by FammyFams** [tchellomello/python-ring-doorbell#315]
im getting this running it just the initiation. 

Password: 
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ring_doorbell\auth.py", line 67, in fetch_token
    token = self._oauth.fetch_token(
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests_oauthlib\oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 451, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "a:/Users/matth/Desktop/ring camera for printer/ring-video-download.py", line 44, in <module>
    main()
  File "a:/Users/matth/Desktop/ring camera for printer/ring-video-download.py", line 31, in main
    auth.fetch_token(username, password)
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ring_doorbell\auth.py", line 75, in fetch_token
    raise Requires2FAError from ex
ring_doorbell.exceptions.Requires2FAError
PS A:\Users\matth\Desktop\ring camera for printer>

**Comment by MackHartley** [comment]
Getting the same thing

**Comment by sdb9696** [comment]
This is now updated and working in master from PR https://github.com/tchellomello/python-ring-doorbell/pull/358
