### ISSUE TITLE
Auth flow does not ask user for 2FA code, fails on this step

### ISSUE THREAD

**Issue by MackHartley** [tchellomello/python-ring-doorbell#356]
Hey there, trying to use this library but the demo example fails. For example:

_Demo code from readme plus a print statement_
```
def main():
    if cache_file.is_file():
        auth = Auth("MyProject/1.0", json.loads(cache_file.read_text()), token_updated)
    else:
        username = input("Username: ")
        password = getpass.getpass("Password: ")
        auth = Auth("MyProject/1.0", None, token_updated)
        try:
            auth.fetch_token(username, password)
        except MissingTokenError:
            print("Hello world - PRINT TEST HERE")
            auth.fetch_token(username, password, otp_callback())
```

In this demo code, the print statement at the end is never triggered. This is an issue because it appears that line needs to run in order to prompt the dev to provide the 2FA code. Any idea how to fix this? I've spent a few hours on my own trying to debug this

Full error:
```
Traceback (most recent call last):
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\ring_doorbell\auth.py", line 66, in fetch_token
    token = self._oauth.fetch_token(
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_oauthlib\oauth2_session.py", line 406, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 451, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\ringdownload.py", line 42, in <module>
    main()
  File ".\ringdownload.py", line 30, in main
    auth.fetch_token(username, password)
  File "C:\Users\hartl\AppData\Local\Programs\Python\Python38\lib\site-packages\ring_doorbell\auth.py", line 74, in fetch_token
    raise Requires2FAError from ex
ring_doorbell.exceptions.Requires2FAError
```

**Comment by MackHartley** [comment]
For anyone reading this, I think if you comment out the three lines below you can force the script to ask for your 2FA. You might need to uncomment this out after the first run though so you used the cached 2FA key.

```
        # try:
        #     auth.fetch_token(username, password)
        # except MissingTokenError:
```

**Comment by MackHartley** [comment]
Update: That doesn't seem to work, I don't get sent 2FA codes unless that `try` case executes. I tried hacking it by running once with the `try` available to get a code, then running with it commented and using the code, but that doesnt work either

**Comment by sdb9696** [comment]
This is now updated and working in master from PR https://github.com/tchellomello/python-ring-doorbell/pull/358
