### ISSUE TITLE
Further analysis of issue #390

### ISSUE THREAD

**Issue by JPAssoc** [tchellomello/python-ring-doorbell#392]
I thought it might help to start a new issue here as the previous one is getting a bit cluttered.

I'm running the Ring part of my app on my Mac at the moment (although I would at some point like to put the whole lot on the Raspberry Pi, but that's another thing altogether). It uses the event listener part of your API to receive notifications of events on the various Ring devices in my network. For a time, this was working fine, receiving every event from every device. But then, following a restart, it reverted back to the behaviour I'd noted before, which was to only deliver events from one device - the latest one added to the network, in fact - a stick-up camera.

I was wondering if there was some issue with the data at the Ring end of things, so I changed the app ID and re-ran the process. It worked perfectly. I then carried out a whole series of other tests with different/same app IDs, and these are the results. I deleted both the .cache files after every run, BTW, and went through the log-in/2FA process every time.

App ID Ring2Byron/1.0 only delivers events from latest device
Change to Ring2Byron - delivers from ALL devices
Change back to Ring2Byron/1.0 - only delivers events from latest device
Change back to Ring2Byron - only delivers events from latest device
Change to Ring2Byron10 - delivers from ALL devices
Change back to Ring2Byron - only delivers events from latest device
Change back to Ring2Byron10 - only delivers events from latest device
Change to Ring2Byron100 - delivers from ALL devices

Does this help with identifying where the problem might lie?

**Comment by JPAssoc** [comment]
Many thanks - that makes perfect sense. I've obviously been a bit quick to clear out the cached credentials file :)

**Comment by JPAssoc** [comment]
Well, that worked brilliantly for a week and a half. Occasionally I got an exception like this: 

2024-08-08 23:17:29,389 - Unexpected exception during read
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 726, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
2024-08-08 23:17:29,889 - Succesfully logged in to MCS endpoint

but as you can see, it recovered.

HOWEVER, I had a more catastrophic failure a couple of days ago, which seems to have rendered my login invalid:

2024-08-12 14:22:47,664 - Unexpected exception during read
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 186, in _do_writer_close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
TimeoutError: SSL shutdown timed out
2024-08-12 14:22:47,676 - Unexpected exception during read
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 186, in _do_writer_close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
TimeoutError: SSL shutdown timed out
2024-08-12 14:22:47,683 - Unexpected exception during read
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 671, in _listen
    elif msg := await self._receive_msg():
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 276, in _receive_msg
    r = await self.reader.readexactly(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 717, in readexactly
    raise self._exception
  File "/home/pi/.local/lib/python3.11/site-packages/firebase_messaging/fcmpushclient.py", line 186, in _do_writer_close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
TimeoutError: SSL shutdown timed out
2024-08-12 14:22:47,691 - Shutting down push receiver due to 3 sequential errors of type ErrorType.CONNECTION
2024-08-12 14:22:47,704 - FCMClient has shutdown

All attempts to use that login now fail to connect with the FCM client. Any idea why this doesn't happen with the standard Ring app?!

**Comment by sdb9696** [comment]
So it seems the legacy api version of firebase that the ring events use was decommissioned a couple of weeks ago. I have upgraded the library to support the new api version and I can confirm it is working for me again.

Note that to use the listener in the latest version of the library you will need to migrate to the async version of the library. The [readme code example is updated](https://github.com/tchellomello/python-ring-doorbell#initializing-your-ring-object) to explain how to do this.

Let me know if you have any issues.
