### ISSUE TITLE
Missing dependencies (typing_extensions)

### ISSUE THREAD

**Issue by zeronounours** [tchellomello/python-ring-doorbell#412]
Since the latest release (0.9.0), the code use the lib `typing_extensions` which is not declared as a dependency, causing execution issues.

The issue was introduced with #361.

```
Traceback (most recent call last):
[…]
  File "/usr/local/lib/python3.12/site-packages/ring_doorbell/__init__.py", line 7, in <module>
    from ring_doorbell.auth import Auth
  File "/usr/local/lib/python3.12/site-packages/ring_doorbell/auth.py", line 28, in <module>
    from ring_doorbell.util import _DeprecatedSyncApiHandler
  File "/usr/local/lib/python3.12/site-packages/ring_doorbell/util.py", line 14, in <module>
    from typing_extensions import Concatenate, ParamSpec, TypeVar
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by sdb9696** [comment]
Many thanks for reporting this. It got missed in the CI as typing_extensions is a dependency of another development dependency. This is now released to production in 0.9.1.
