### ISSUE TITLE
what mean this error?

### ISSUE THREAD

**Issue by 10der** [tchellomello/python-ring-doorbell#82]
2018-01-16 12:17:08,979 ERROR    No handlers could be found for logger "ring_doorbell"
2018-01-16 12:17:08,981 ERROR    Traceback (most recent call last):
2018-01-16 12:17:08,982 ERROR      File "/home/pi/ring/myring.py", line 65, in <module>

2018-01-16 12:17:08,984 ERROR      File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 53, in __init__
2018-01-16 12:17:08,986 ERROR    self._process_cached_session()
2018-01-16 12:17:08,986 ERROR      File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 79, in _process_cached_session
2018-01-16 12:17:08,987 ERROR    req = self.query(url, raw=True)
2018-01-16 12:17:08,988 ERROR      File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 172, in query
2018-01-16 12:17:08,988 ERROR    req = self.session.get((url), params=urlencode(params))
2018-01-16 12:17:08,989 ERROR      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
2018-01-16 12:17:08,992 ERROR    return self.request('GET', url, **kwargs)
2018-01-16 12:17:08,993 ERROR      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
2018-01-16 12:17:08,994 ERROR    resp = self.send(prep, **send_kwargs)
2018-01-16 12:17:08,994 ERROR      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
2018-01-16 12:17:08,996 ERROR    r = adapter.send(request, **kwargs)
2018-01-16 12:17:08,996 ERROR      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
2018-01-16 12:17:08,999 ERROR    raise ConnectionError(e, request=request)
2018-01-16 12:17:09,000 ERROR    requests.exceptions
2018-01-16 12:17:09,000 ERROR    .
2018-01-16 12:17:09,001 ERROR    ConnectionError
2018-01-16 12:17:09,001 ERROR    :
2018-01-16 12:17:09,002 ERROR    HTTPSConnectionPool(host='api.ring.com', port=443): Max retries exceeded with url: /clients_api/ring_devices?auth_token=vA9pYT9ExX6iWxDLLDqp&api_version=9 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75e8d270>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by 10der** [comment]
no internet access. 
thank you. closed!
